import { withOpacity } from '../colorUtils'
import { theme } from '../theme'
import type { ThemeAccent, ThemeDefinition } from './types'

const buildAccent = (base: string, light: string, dark: string): ThemeAccent => ({
  DEFAULT: base,
  light,
  dark,
  bg: withOpacity(base, 0.1),
  border: withOpacity(base, 0.5),
})

export const darkTheme: ThemeDefinition = {
  id: 'dark',
  name: 'Dark',
  isDark: true,
  colors: {
    background: theme.colors.background,
    text: theme.colors.text,
    border: theme.colors.border,
    accent: theme.colors.accent,
    status: theme.colors.status,
    terminal: {
      background: theme.colors.background.secondary,
      foreground: theme.colors.text.primary,
      cursor: theme.colors.text.primary,
      selection: theme.colors.selection.bg,
      black: theme.colors.background.elevated,
      red: theme.colors.accent.red.DEFAULT,
      green: theme.colors.accent.green.DEFAULT,
      yellow: theme.colors.accent.yellow.DEFAULT,
      blue: theme.colors.accent.blue.DEFAULT,
      magenta: theme.colors.accent.purple.DEFAULT,
      cyan: theme.colors.accent.cyan.DEFAULT,
      white: theme.colors.text.primary,
      brightBlack: theme.colors.background.hover,
      brightRed: theme.colors.accent.red.light,
      brightGreen: theme.colors.accent.green.light,
      brightYellow: theme.colors.accent.yellow.light,
      brightBlue: theme.colors.accent.blue.light,
      brightMagenta: theme.colors.accent.purple.light,
      brightCyan: theme.colors.accent.cyan.light,
      brightWhite: theme.colors.text.primary,
    },
  },
}

const lightAccent = {
  blue: buildAccent('#2563eb', '#3b82f6', '#1d4ed8'),
  green: buildAccent('#16a34a', '#22c55e', '#15803d'),
  amber: buildAccent('#d97706', '#f59e0b', '#b45309'),
  red: buildAccent('#dc2626', '#ef4444', '#b91c1c'),
  violet: buildAccent('#7c3aed', '#8b5cf6', '#6d28d9'),
  purple: buildAccent('#9333ea', '#a855f7', '#7e22ce'),
  magenta: buildAccent('#db2777', '#ec4899', '#be185d'),
  yellow: buildAccent('#ca8a04', '#eab308', '#a16207'),
  cyan: buildAccent('#0891b2', '#06b6d4', '#0e7490'),
  copilot: buildAccent('#BD79CC', '#D9A6E5', '#8F4A9E'),
}

const tokyonightAccent = {
  blue: buildAccent('#7aa2f7', '#89ddff', '#3d59a1'),
  green: buildAccent('#9ece6a', '#73daca', '#41a6b5'),
  amber: buildAccent('#e0af68', '#ff9e64', '#d19a66'),
  red: buildAccent('#f7768e', '#ff8c9a', '#db4b4b'),
  violet: buildAccent('#bb9af7', '#c9b0ff', '#9d7cd8'),
  purple: buildAccent('#9d7cd8', '#bb9af7', '#7e5db2'),
  magenta: buildAccent('#ff007c', '#ff4d9d', '#c71f6e'),
  yellow: buildAccent('#e0af68', '#ffcb6b', '#d19a66'),
  cyan: buildAccent('#7dcfff', '#b4f9f8', '#2ac3de'),
  copilot: buildAccent('#bb9af7', '#c9b0ff', '#9d7cd8'),
}

const catppuccinMacchiatoAccent = {
  blue: buildAccent('#8aadf4', '#91d7e3', '#7dc4e4'),
  green: buildAccent('#a6da95', '#8bd5ca', '#40a02b'),
  amber: buildAccent('#f5a97f', '#eed49f', '#fe640b'),
  red: buildAccent('#ed8796', '#f5bde6', '#d20f39'),
  violet: buildAccent('#c6a0f6', '#f5bde6', '#8839ef'),
  purple: buildAccent('#c6a0f6', '#f5bde6', '#8839ef'),
  magenta: buildAccent('#f5bde6', '#f5bde6', '#ea76cb'),
  yellow: buildAccent('#eed49f', '#f5e0dc', '#df8e1d'),
  cyan: buildAccent('#8bd5ca', '#91d7e3', '#179299'),
  copilot: buildAccent('#c6a0f6', '#f5bde6', '#8839ef'),
}

export const tokyonightTheme: ThemeDefinition = {
  id: 'tokyonight',
  name: 'Tokyo Night',
  isDark: true,
  colors: {
    background: {
      primary: '#1a1b26',
      secondary: '#16161e',
      tertiary: '#1f2335',
      elevated: '#24283b',
      hover: '#292e42',
      active: '#3b4261',
    },
    text: {
      primary: '#c0caf5',
      secondary: '#a9b1d6',
      tertiary: '#737aa2',
      muted: '#565f89',
      inverse: '#1a1b26',
    },
    border: {
      default: '#3b4261',
      subtle: '#292e42',
      strong: '#545c7e',
      focus: tokyonightAccent.blue.DEFAULT,
    },
    accent: tokyonightAccent,
    status: {
      info: '#7dcfff',
      success: '#9ece6a',
      warning: '#e0af68',
      error: '#f7768e',
    },
    terminal: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      selection: withOpacity(tokyonightAccent.blue.DEFAULT, 0.3),
      black: '#414868',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#c0caf5',
      brightBlack: '#545c7e',
      brightRed: '#ff8c9a',
      brightGreen: '#73daca',
      brightYellow: '#ff9e64',
      brightBlue: '#89ddff',
      brightMagenta: '#c9b0ff',
      brightCyan: '#b4f9f8',
      brightWhite: '#c0caf5',
    },
  },
}

export const catppuccinMacchiatoTheme: ThemeDefinition = {
  id: 'catppuccin-macchiato',
  name: 'Catppuccin Macchiato',
  isDark: true,
  colors: {
    background: {
      primary: '#24273a',
      secondary: '#1e2030',
      tertiary: '#181926',
      elevated: '#363a4f',
      hover: '#494d64',
      active: '#5b6078',
    },
    text: {
      primary: '#cad3f5',
      secondary: '#b8c0e0',
      tertiary: '#a5adcb',
      muted: '#6e738d',
      inverse: '#24273a',
    },
    border: {
      default: '#5b6078',
      subtle: '#494d64',
      strong: '#6e738d',
      focus: catppuccinMacchiatoAccent.blue.DEFAULT,
    },
    accent: catppuccinMacchiatoAccent,
    status: {
      info: '#91d7e3',
      success: '#a6da95',
      warning: '#eed49f',
      error: '#ed8796',
    },
    terminal: {
      background: '#24273a',
      foreground: '#cad3f5',
      cursor: '#f4dbd6',
      selection: withOpacity(catppuccinMacchiatoAccent.blue.DEFAULT, 0.3),
      black: '#494d64',
      red: '#ed8796',
      green: '#a6da95',
      yellow: '#eed49f',
      blue: '#8aadf4',
      magenta: '#f5bde6',
      cyan: '#8bd5ca',
      white: '#b8c0e0',
      brightBlack: '#5b6078',
      brightRed: '#ed8796',
      brightGreen: '#a6da95',
      brightYellow: '#eed49f',
      brightBlue: '#8aadf4',
      brightMagenta: '#f5bde6',
      brightCyan: '#8bd5ca',
      brightWhite: '#a5adcb',
    },
  },
}

export const lightTheme: ThemeDefinition = {
  id: 'light',
  name: 'Light',
  isDark: false,
  colors: {
    background: {
      primary: '#ffffff',
      secondary: '#f6f8fa',
      tertiary: '#eaeef2',
      elevated: '#ffffff',
      hover: '#eaeef2',
      active: '#d1d9e0',
    },
    text: {
      primary: '#1f2328',
      secondary: '#656d76',
      tertiary: '#8c959f',
      muted: '#8c959f',
      inverse: '#ffffff',
    },
    border: {
      default: '#d1d9e0',
      subtle: '#eaeef2',
      strong: '#d1d9e0',
      focus: lightAccent.blue.DEFAULT,
    },
    accent: lightAccent,
    status: {
      info: '#0891b2',
      success: '#16a34a',
      warning: '#d97706',
      error: '#dc2626',
    },
    terminal: {
      background: '#f6f8fa',
      foreground: '#1f2328',
      cursor: '#1f2328',
      selection: withOpacity(lightAccent.blue.DEFAULT, 0.2),
      black: '#1f2328',
      red: lightAccent.red.DEFAULT,
      green: lightAccent.green.DEFAULT,
      yellow: lightAccent.amber.DEFAULT,
      blue: lightAccent.blue.DEFAULT,
      magenta: lightAccent.purple.DEFAULT,
      cyan: lightAccent.cyan.DEFAULT,
      white: '#57606a',
      brightBlack: '#656d76',
      brightRed: lightAccent.red.light,
      brightGreen: lightAccent.green.light,
      brightYellow: lightAccent.amber.light,
      brightBlue: lightAccent.blue.light,
      brightMagenta: lightAccent.purple.light,
      brightCyan: lightAccent.cyan.light,
      brightWhite: '#24292f',
    },
  },
}
