name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # For GitHub Actions, use their runner image
    # For act local testing, use our custom image via actrc config
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install system dependencies (GitHub Actions)
        # Only run on GitHub Actions, not in act (which uses pre-built image)
        if: ${{ !env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Setup Node.js (GitHub Actions)
        # Skip in act since Node is pre-installed in custom image
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust (GitHub Actions)
        # Skip in act since Rust is pre-installed in custom image
        if: ${{ !env.ACT }}
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Node dependencies
        run: npm ci

      - name: Run full test suite (lint, TS, clippy, frontend, Rust, build)
        run: npm run test
