name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SCHALTWERK_PM: bun
    # For GitHub Actions, use their runner image
    # For act local testing, use our custom image via actrc config
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Restore system package cache
        if: ${{ !env.ACT }}
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/system-packages.txt') }}

      - name: Install system dependencies (GitHub Actions)
        # Only run on GitHub Actions, not in act (which uses pre-built image)
        if: ${{ !env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Setup Node.js (GitHub Actions)
        # Skip in act since Node is pre-installed in custom image
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Setup Bun
        if: ${{ !env.ACT }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.16'

      - name: Setup Rust (GitHub Actions)
        # Skip in act since Rust is pre-installed in custom image
        if: ${{ !env.ACT }}
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Restore cargo home cache
        id: cache_cargo_home_restore
        if: ${{ !env.ACT }}
        uses: actions/cache/restore@v4
        with:
          # Skip caching src-tauri/target because the debug artifacts exceed 2 GB and
          # the post-job tar archive started timing out after the objc2 upgrade.
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-nextest and cargo-shear
        run: |
          if ! command -v cargo-nextest >/dev/null 2>&1; then
            cargo install cargo-nextest --locked
          fi
          if ! command -v cargo-shear >/dev/null 2>&1; then
            cargo install cargo-shear
          fi

      - name: Install dependencies
        run: |
          rm -rf node_modules
          node scripts/package-manager.mjs install --frozen-lockfile

          # Install MCP server dependencies
          if [ -d "mcp-server" ]; then
            echo "Installing MCP server dependencies..."
            cd mcp-server
            node ../scripts/package-manager.mjs install --frozen-lockfile
            cd ..
          fi

      - name: Run full test suite (lint, shear, nextest, build)
        run: node scripts/package-manager.mjs run test

      - name: Save cargo home cache
        if: always() && !cancelled() && steps.cache_cargo_home_restore.outputs.cache-hit != 'true' && !env.ACT
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
