name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      schaltwerk: ${{ steps.filter.outputs.schaltwerk }}
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v5

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            schaltwerk:
              - 'src/**'
              - 'src-tauri/**'
              - 'mcp-server/**'
              - 'scripts/**'
              - 'package.json'
              - 'bun.lock'
              - 'justfile'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - 'vite.config.ts'
              - 'postcss.config.js'
              - 'tailwind.config.js'
              - 'eslint.config.js'
              - 'eslint-rules/**'
            workflows:
              - '.github/workflows/**'

  lint-typescript:
    name: TypeScript Lint & Format
    runs-on: ubuntu-latest
    needs: changed
    if: ${{ needs.changed.outputs.schaltwerk == 'true' || needs.changed.outputs.workflows == 'true' || github.event_name == 'push' }}
    env:
      SCHALTWERK_PM: bun
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.16'

      - name: Install dependencies
        run: |
          node scripts/package-manager.mjs install --frozen-lockfile
          if [ -d "mcp-server" ]; then
            cd mcp-server && node ../scripts/package-manager.mjs install --frozen-lockfile && cd ..
          fi

      - name: Run TypeScript lints
        run: |
          node scripts/package-manager.mjs run lint
          node scripts/package-manager.mjs run lint:ts
          node scripts/package-manager.mjs run lint:mcp

  lint-rust:
    name: Rust Lint & Hygiene
    runs-on: ubuntu-latest
    needs: changed
    if: ${{ needs.changed.outputs.schaltwerk == 'true' || needs.changed.outputs.workflows == 'true' || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Restore cargo home cache
        id: cache_cargo_home_restore
        if: ${{ !env.ACT }}
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo tools
        run: |
          cargo install cargo-shear || true

      - name: Run Rust lints
        run: |
          cd src-tauri
          cargo clippy --all-features -- -D warnings
          cargo shear

      - name: Save cargo home cache
        if: always() && !cancelled() && steps.cache_cargo_home_restore.outputs.cache-hit != 'true' && !env.ACT
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: changed
    if: ${{ needs.changed.outputs.schaltwerk == 'true' || needs.changed.outputs.workflows == 'true' || github.event_name == 'push' }}
    env:
      SCHALTWERK_PM: bun
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.16'

      - name: Install dependencies
        run: |
          node scripts/package-manager.mjs install --frozen-lockfile
          if [ -d "mcp-server" ]; then
            cd mcp-server && node ../scripts/package-manager.mjs install --frozen-lockfile && cd ..
          fi

      - name: Run frontend tests
        run: |
          node scripts/package-manager.mjs run test:frontend
          node scripts/package-manager.mjs run test:mcp

  test-rust:
    name: Rust Tests & Build
    runs-on: ubuntu-latest
    needs: changed
    if: ${{ needs.changed.outputs.schaltwerk == 'true' || needs.changed.outputs.workflows == 'true' || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Restore cargo home cache
        id: cache_cargo_home_restore
        if: ${{ !env.ACT }}
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked || true

      - name: Run Rust tests
        run: |
          cd src-tauri
          cargo nextest run --all-features --status-level fail --failure-output immediate

      - name: Build Rust
        run: |
          cd src-tauri
          cargo build

      - name: Save cargo home cache
        if: always() && !cancelled() && steps.cache_cargo_home_restore.outputs.cache-hit != 'true' && !env.ACT
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

  results:
    name: CI Results (required)
    needs: [changed, lint-typescript, lint-rust, test-frontend, test-rust]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs
        shell: bash
        run: |
          echo "lint-typescript: ${{ needs.lint-typescript.result }}"
          echo "lint-rust      : ${{ needs.lint-rust.result }}"
          echo "test-frontend  : ${{ needs.test-frontend.result }}"
          echo "test-rust      : ${{ needs.test-rust.result }}"
          
          # If no relevant changes, succeed
          if [[ '${{ needs.changed.outputs.schaltwerk }}' != 'true' && '${{ needs.changed.outputs.workflows }}' != 'true' && '${{ github.event_name }}' != 'push' ]]; then
            echo 'No relevant changes -> CI passed.'
            exit 0
          fi
          
          # All jobs must succeed
          [[ '${{ needs.lint-typescript.result }}' == 'success' ]] || { echo 'lint-typescript failed'; exit 1; }
          [[ '${{ needs.lint-rust.result }}' == 'success' ]] || { echo 'lint-rust failed'; exit 1; }
          [[ '${{ needs.test-frontend.result }}' == 'success' ]] || { echo 'test-frontend failed'; exit 1; }
          [[ '${{ needs.test-rust.result }}' == 'success' ]] || { echo 'test-rust failed'; exit 1; }
          
          echo 'All checks passed!'
